import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Target, Filter, Settings, FileText, Download, Sparkles, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface GrowthGuidePanelProps {
    isOpen: boolean;
    onClose: () => void;
}

const GrowthGuidePanel = ({ isOpen, onClose }: GrowthGuidePanelProps) => {
    const [step, setStep] = useState<"form" | "loading" | "result">("form");
    const [formData, setFormData] = useState({
        goal: "Increase Followers",
        contentType: "Both",
        frequency: "Daily",
        targetAudience: ""
    });
    const [planContent, setPlanContent] = useState("");

    const handleGenerate = () => {
        setStep("loading");
        // Simulate AI generation time
        setTimeout(() => {
            const plan = `
GROWTH PLAN REPORT
------------------
Goal: ${formData.goal}
Content Focus: ${formData.contentType}
Posting Cadence: ${formData.frequency}
Target Audience: ${formData.targetAudience || "General Audience"}

ACTION PLAN:
1. Optimize Profile
   - Ensure a strong bio that clearly states value.
   - Use a clear profile picture and clean highlights.
   
2. Content Strategy
   ${formData.contentType === "Reels" || formData.contentType === "Both" ? "- Post 3-4 Reels per week focusing on trending audio and high-value hooks." : "- Focus on high-quality carousels and engaging single-image posts."}
   ${formData.frequency === "Daily" ? "- Maintain your daily schedule to signal high activity to the algorithm." : "- Ensure consistency matching your chosen frequency."}
   
3. Engagement & Outreach
   - Spend 15 mins daily engaging with larger accounts in your niche.
   - Reply to comments within the first hour of posting.
   
4. Performance Tracking
   - Check Insights weekly to double down on formats that work.
------------------
Generated by InstaAura Assistant
      `.trim();
            setPlanContent(plan);
            setStep("result");
        }, 2500);
    };

    const handleDownload = () => {
        const blob = new Blob([planContent], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "InstaAura_Growth_Plan.txt";
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const resetState = () => {
        setStep("form");
        setFormData({
            goal: "Increase Followers",
            contentType: "Both",
            frequency: "Daily",
            targetAudience: ""
        });
        setPlanContent("");
        onClose();
    };

    return (
        <AnimatePresence>
            {isOpen && (
                <>
                    {/* Overlay */}
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        onClick={resetState}
                        className="fixed inset-0 bg-background/80 backdrop-blur-sm z-40"
                    />

                    {/* Side Panel */}
                    <motion.div
                        initial={{ x: "100%" }}
                        animate={{ x: 0 }}
                        exit={{ x: "100%" }}
                        transition={{ type: "spring", damping: 25, stiffness: 200 }}
                        className="fixed inset-y-0 right-0 w-full max-w-md bg-card/95 backdrop-blur-xl border-l border-border z-50 flex flex-col shadow-2xl shadow-primary/10"
                    >
                        {/* Header */}
                        <div className="flex flex-col p-6 border-b border-border/50 bg-background/50 relative">
                            <div className="absolute top-2 left-6 flex items-center gap-1.5 opacity-70">
                                <div className="w-1.5 h-1.5 rounded-full bg-orange-500 animate-pulse" />
                                <span className="text-[10px] uppercase tracking-widest font-bold text-orange-400">Automation</span>
                            </div>
                            <div className="flex items-center justify-between mt-2">
                                <div className="flex items-center gap-3">
                                    <div className="p-2 bg-primary/20 rounded-lg">
                                        <Sparkles className="w-5 h-5 text-primary" />
                                    </div>
                                    <h2 className="text-xl font-bold">Growth Guide</h2>
                                </div>
                                <Button variant="ghost" size="icon" onClick={resetState} className="rounded-full hover:bg-muted">
                                    <X className="w-5 h-5" />
                                </Button>
                            </div>
                        </div>

                        {/* Content Area */}
                        <div className="flex-1 overflow-y-auto p-6 scrollbar-hide">
                            {step === "form" && (
                                <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
                                    <p className="text-muted-foreground text-sm leading-relaxed mb-6">
                                        Answer a few simple questions, and our AI will build your personalized Instagram action plan.
                                    </p>

                                    {/* Goal */}
                                    <div className="space-y-3">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/90">
                                            <Target className="w-4 h-4 text-primary" /> Primary Goal
                                        </label>
                                        <div className="relative">
                                            <select
                                                className="w-full bg-background/50 border border-border rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary appearance-none transition-all hover:border-primary/50"
                                                value={formData.goal}
                                                onChange={(e) => setFormData({ ...formData, goal: e.target.value })}
                                            >
                                                <option value="Increase Followers">Increase Followers</option>
                                                <option value="Boost Engagement">Boost Engagement</option>
                                                <option value="Drive Sales">Drive Sales</option>
                                            </select>
                                        </div>
                                    </div>

                                    {/* Content Focus */}
                                    <div className="space-y-3">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/90">
                                            <Filter className="w-4 h-4 text-primary" /> Content Focus
                                        </label>
                                        <select
                                            className="w-full bg-background/50 border border-border rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary appearance-none transition-all hover:border-primary/50"
                                            value={formData.contentType}
                                            onChange={(e) => setFormData({ ...formData, contentType: e.target.value })}
                                        >
                                            <option value="Both">Both (Reels & Posts)</option>
                                            <option value="Reels">Reels Only</option>
                                            <option value="Posts">Image Posts & Carousels</option>
                                        </select>
                                    </div>

                                    {/* Frequency */}
                                    <div className="space-y-3">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/90">
                                            <Settings className="w-4 h-4 text-primary" /> Posting Frequency
                                        </label>
                                        <select
                                            className="w-full bg-background/50 border border-border rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary appearance-none transition-all hover:border-primary/50"
                                            value={formData.frequency}
                                            onChange={(e) => setFormData({ ...formData, frequency: e.target.value })}
                                        >
                                            <option value="Daily">Daily</option>
                                            <option value="Weekly">3-4 times a week</option>
                                            <option value="Rarely">Once a week or less</option>
                                        </select>
                                    </div>

                                    {/* Target Audience */}
                                    <div className="space-y-3">
                                        <label className="text-sm font-medium flex items-center gap-2 text-foreground/90">
                                            <FileText className="w-4 h-4 text-primary" /> Target Audience <span className="text-muted-foreground font-normal text-xs">(Optional)</span>
                                        </label>
                                        <input
                                            type="text"
                                            className="w-full bg-background/50 border border-border rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-1 focus:ring-primary transition-all hover:border-primary/50"
                                            placeholder="e.g. Fitness enthusiasts in their 20s"
                                            value={formData.targetAudience}
                                            onChange={(e) => setFormData({ ...formData, targetAudience: e.target.value })}
                                        />
                                    </div>

                                    <div className="pt-6">
                                        <Button
                                            className="w-full bg-primary text-primary-foreground hover:bg-primary/90 glow-primary h-12 rounded-lg font-semibold"
                                            onClick={handleGenerate}
                                        >
                                            <Sparkles className="w-4 h-4 mr-2" />
                                            Generate AI Plan
                                        </Button>
                                    </div>
                                </motion.div>
                            )}

                            {step === "loading" && (
                                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="h-full flex flex-col items-center justify-center space-y-6">
                                    <div className="relative">
                                        <div className="absolute inset-0 bg-primary/20 blur-xl rounded-full" />
                                        <Loader2 className="w-12 h-12 text-primary animate-spin relative z-10" />
                                    </div>
                                    <div className="text-center space-y-2">
                                        <h3 className="text-lg font-medium text-foreground">Analyzing Strategy</h3>
                                        <p className="text-sm text-muted-foreground">Building your personalized growth plan...</p>
                                    </div>
                                </motion.div>
                            )}

                            {step === "result" && (
                                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} className="space-y-6 h-full flex flex-col">
                                    <div className="flex-1 p-5 bg-background/50 rounded-xl border border-border/50 font-mono text-sm text-foreground/80 whitespace-pre-wrap overflow-y-auto custom-scrollbar leading-relaxed">
                                        {planContent}
                                    </div>

                                    <div className="pt-4 border-t border-border/50">
                                        <Button
                                            variant="outline"
                                            className="w-full border-primary/40 text-primary hover:bg-primary/10 hover:text-primary glow-primary h-12 rounded-lg font-semibold"
                                            onClick={handleDownload}
                                        >
                                            <Download className="w-4 h-4 mr-2" />
                                            Download Plan (TXT)
                                        </Button>
                                    </div>
                                </motion.div>
                            )}
                        </div>
                    </motion.div>
                </>
            )}
        </AnimatePresence>
    );
};

export default GrowthGuidePanel;
